name: run-2019
run-name: Run AoC 2019 problems
on: [push]
jobs:
  test-aoc-library:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
            cache: 'pip'
        run: pip install -r requirements.txt
      - name: Run aoc lib test
        run: pytest aoc/__init__.py
  test-2019-problems:
    runs-on: ubuntu-latest
    needs: test-aoc-library
    strategy:
      matrix:
        problem: ["01", "02", "03"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
            cache: 'pip'
        run: pip install -r requirements.txt
      - name: Decrypt input ${{ matrix.problem }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$AOC_SECRET" --output 2019/input.${{ matrix.problem }}.txt 2019/input.${{ matrix.problem }}.txt.gpg
        env:
          AOC_SECRET: ${{ secrets.AOC_SECRET }}
      - name: Run p01
        env:
          PYTHONPATH: ${{ github.workspace }}/aoc
        run: |
          echo $PYTHONPATH
          mkdir -p 2019/aoc
          cp -r aoc/* 2019/aoc
          time python 2019/adv01-r.py < 2019/input.${{ matrix.problem }}.txt > out.txt
          diff out.txt 2019/output.${{ matrix.problem }}.txt
