name: run-2019
run-name: Run AoC 2019 problems
on: [push]
jobs:
  test-aoc-library:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
            cache: 'pip'
      - name: Install pip
        run: pip install -r requirements.txt
      - name: Run aoc lib test
        run: pytest aoc/__init__.py
  test-problem:
    runs-on: ubuntu-latest
    needs: test-aoc-library
    strategy:
      matrix:
        year: ["2015", "2019"]
        problem: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                  "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
            cache: 'pip'
      - name: Install pip
        run: pip install -r requirements.txt
      - name: Decrypt input ${{ matrix.problem }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$AOC_SECRET" --output ${{ matrix.year }}/input.${{ matrix.problem }}.txt ${{ matrix.year }}/encrypted_input/input.${{ matrix.problem }}.txt.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="$AOC_SECRET" --output ${{ matrix.year }}/output.${{ matrix.problem }}.txt ${{ matrix.year }}/encrypted_input/output.${{ matrix.problem }}.txt.gpg
        env:
          AOC_SECRET: ${{ secrets.AOC_SECRET }}
      - name: Run problem ${{ matrix.year }} ${{ matrix.problem }}
        env:
          PYTHONPATH: ${{ github.workspace }}/aoc
        run: |
          mkdir -p ${{ matrix.year }}/aoc
          cp -r aoc/* ${{ matrix.year }}/aoc
          time python ${{ matrix.year }}/adv${{ matrix.problem }}-r.py < ${{ matrix.year }}/input.${{ matrix.problem }}.txt > output.${{ matrix.problem }}.txt
      - name: Check answer ${{ matrix.problem }}
        run: diff output.${{ matrix.problem }}.txt ${{ matrix.year }}/output.${{ matrix.problem }}.txt
