name: run-2019
run-name: Run AoC 2019 problems
on: [push]
jobs:
  test-aoc-library:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
            python-version: 3.12
      - name: Check Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install pip
        run:  python -m pip install --upgrade pip
      - name: Install numpy and pytest
        run:  pip install numpy pytest
      - name: Run aoc lib test
        run: pytest aoc/__init__.py
      - name: Decrypt input 01
        run: gpg --quiet --batch --yes --decrypt --passphrase="$AOC_SECRET" --output 2019/input.01.txt 2019/input.01.txt.gpg
        env:
          AOC_SECRET: ${{ secrets.AOC_SECRET }}
      - name: Run p01
        run: time python3.12 2019/adv01-r.py < 2019/input.01.txt
