name: run-2019
run-name: Run AoC 2019 problems
on: [push]
jobs:
  check-install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
            python-version: 3.12
      - name: Check Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run aoc lib test
        run: python aoc/__init__.py
